pipeline:
  name: Demo Pipeline Github connect
  identifier: demo_pipeline_github
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: newdelegate
        repoName: demoharness
        build: <+input>
  stages:
    - stage:
        name: build from two repos
        identifier: build_from_two_repos
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Check Node Version
                  identifier: check_node_version
                  spec:
                    shell: Bash
                    command: |
                      node --version
                      npm --version
                      sh script.sh
                    artifacts:
                      primary:
                        sources:
                          - name: Cypress JUnit Reports
                            path: cypress/results
                    connectorRef: account.harnessImage
                    delegateSelectors:
                      - docker-delegate-latest
              - step:
                  name: Publish Cypress Test Results
                  identifier: publish_results
                  type: RunTests
                  spec:
                    language: Java
                    buildTool: Maven
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - cypress/results/*.xml
                    connectorRef: account.harnessImage
                    delegateSelectors:
                      - docker-delegate-latest
