pipeline:
  name: Demo Pipeline Github connect
  identifier: demo_pipeline_github
  stages:
    - stage:
        name: BuildStage
        identifier: build_stage
        type: Build
        spec:
          execution:
            steps:
              - step:
                  name: Clone GitHub Repo
                  identifier: clone_repo
                  type: GitClone
                  spec:
                    connectorRef: Githubconnect
                    repoName: demoharness
                    branch: main
                    delegateSelectors: 
                      - docker-delegate-latest
